// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3Nc-9rmoxzqfYBPUiOsTqtT0gqklc-sU',
    appId: '1:623748298405:web:9efb7ea298e96118113f4c',
    messagingSenderId: '623748298405',
    projectId: 'plantdiseaseapp-6f285',
    authDomain: 'plantdiseaseapp-6f285.firebaseapp.com',
    storageBucket: 'plantdiseaseapp-6f285.appspot.com',
    measurementId: 'G-GQE16VX0B4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXr4ouIXmgSjcPgXRKFY__XUP3EHjKaJA',
    appId: '1:623748298405:android:db78767d87cc8905113f4c',
    messagingSenderId: '623748298405',
    projectId: 'plantdiseaseapp-6f285',
    storageBucket: 'plantdiseaseapp-6f285.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCso0qljvhZ1BMmBUgHult4UMuxF0RkK30',
    appId: '1:623748298405:ios:a34f3021abf47662113f4c',
    messagingSenderId: '623748298405',
    projectId: 'plantdiseaseapp-6f285',
    storageBucket: 'plantdiseaseapp-6f285.appspot.com',
    iosBundleId: 'com.example.plantdiseaseidentifcationml',
  );
}
